version: "3.8"

services:
  sergey-web:
    build: ./task_manager
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn task_manager.wsgi:application --bind 0.0.0.0:8000 --access-logfile -"
    ports:
      - "5432:5432"
    volumes:
      - staticfiles:/usr/src/static/
      - media:/usr/src/media/
    environment:
      - SERVER_PORT:8000

  sergey-nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "86:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/var/html/static/
      - media:/var/html/media/
    restart: always
    depends_on:
      - sergey-web

volumes:
  staticfiles:
  media:

